[package]
name = "miro"
version = "0.1.0"
description = "Terminal emulator"
authors = ["o2sh <ossama-hjaji@live.fr>"]
edition = "2018"
readme = "README.md"
license = "MIT"
repository = "https://github.com/o2sh/miro"

[dependencies]
bitflags = "1.0.1"
failure = "0.1.1"
freetype = "0.3.0"
gl = "0.10.0"
palette = "0.2.1"
serde = "1.0.27"
serde_derive = "1.0.27"
toml = "0.4.5"
harfbuzz-sys = "0.1.15"
libc = "0.2.36"
mio = "0.6.12"
resize = "0.3.0"
servo-fontconfig = "0.4.0"
unicode-width = "0.1.4"
egli = "0.4.0"
euclid = "0.17.0"
serde_json = "1.0"
regex = "1.3.4"
image = "0.23.13"
term = {path = "./term" }

[dependencies.glium]
default-features = false
version = "0.20.0"

[dependencies.x11]
features = ["xlib"]
version = "2.17.2"

[dependencies.xcb]
features = ["shm"]
version = "0.8.1"

[dependencies.xcb-util]
features = [
    "image",
    "icccm",
    "ewmh",
    "misc",
    "shm",
    "keysyms",
]
version = "0.2.0"

[workspace]
members = [
    "term"
]

[features]
debug-escape-sequences = ["term/debug-escape-sequences"]